; Apio project configuration file.
; See https://fpgawars.github.io/apio/docs/project-file for details.

[env:default]
board = colorlight-5a-75b-v8-usb-blaster-write-sram
top-module = main

defines =
    N=4_000_000

